### ISSUE TITLE
Novo bug nos testes

### ISSUE THREAD

**Issue by caikfra** [ProfRonan/matrizes-e-vetores-caikfra#3]
Após a última atualização dos arquivos os testes voltaram a não rodar mais. Poderia me ajudar seu @SeuRonao

**Comment by SeuRonao** [comment]
O bug aconteceu por existir um arquivo com nome `test` na pasta raiz do projeto.
Eu fiz um commit mudando o nome dele.
A forma que o `unittest` do python faz para procurar os testes é justamente procurando arquivos, classes, funções com que comecem com o nome `test`.
